### ISSUE TITLE
The loss of declaration track in Pycharm

### ISSUE THREAD

**Issue by iamlxb3** [patrick-kidger/torchtyping#18]
The typing check is really useful, however, I found it a bit inconvenient to jump right into the source code of torch with Pycharm. It seems the declaration track is lost. Below I give two quick examples.

Everything is ok if the typing is set to torch.Tensor
<img width="256" alt="image" src="https://user-images.githubusercontent.com/6754249/119623459-c3f62080-be3a-11eb-9242-e2251333f376.png">

The track is lost when set to TensorType in torchtyping
<img width="310" alt="image" src="https://user-images.githubusercontent.com/6754249/119623570-e425df80-be3a-11eb-887c-814e66d3c5f4.png">

There is one workaround though, by using Union in typing to include them both. But I think it a bit ugly.

**Comment by patrick-kidger** [comment]
Thanks for the report. This should now be fixed in the latest version, 0.1.3.
