### ISSUE TITLE
Basic mypy integration tests don't work?

### ISSUE THREAD

**Issue by bluenote10** [patrick-kidger/torchtyping#41]
Since the documentation suggest that mypy integration mostly works, I would have expected the following basic things to work.

```py
import torch
from torchtyping import TensorType  # type: ignore


# I'd expect that mixing TensorType with torch.Tensor works. However in
# strict mode this errors with:
# error: Returning Any from function declared to return "Tensor"
def simple_test_a(x: TensorType[(), float]) -> torch.Tensor:
    return x


# I'd expect that .item() has the type in the annotation, and that e.g.
# annotation the function with `-> str` would be a type error. However
# in strict mode this errors with:
# error: Returning Any from function declared to return "float"
def simple_test_b(x: TensorType[(), float]) -> float:
    return x.item()


# I'd expect that mypy is a aware of actual methods of a tensor and
# gives a type check error when calling garbage.
def simple_test_c(x: TensorType[(), float]) -> None:
    x.asdfasdfasdf()
```

Note that the latter two work when using the native `torch.Tensor` as a type annotation.

From what I can tell so far is that mypy actually doesn't understand the meaning of `TensorType` at all. I thought that "mostly works" means that I can expect mypy to produce meaningful type check errors based on the annotations (operations with illegal shape or dtype combinations etc.).

Am I doing something wrong here, or does "mostly works" that it simply completely ignores the type annotations? Kind of unexpected considering the primary motivation of type annotations is to be used in type checking.

**Comment by patrick-kidger** [comment]
TorchTyping is primarily designed for use with runtime type-checking (with typeguard). Static type-checking (mypy) intrinsically isn't capable of e.g. performing shape-checks for tensors.

FWIW I would recommend using [jaxtyping](https://github.com/google/jaxtyping) for any new projects. This has a much smarter design under-the-hood, which means that it should work with any runtime typechecker out-of-the-box (without the patching of typeguard that TorchTyping uses), and has better support for static type checkers. They still won't be able to catch shape errors (as above, this isn't feasible for static type checking), but they will be able to check  the tensor-ness of their argument, and also should't require any fiddling around to get them to work.

(Despite the name, jaxtyping works for any of PyTorch/Tensorflow/NumPy as well.)

**Comment by bluenote10** [comment]
Thanks for the clarification!

In this case this is mostly a matter of documentation then I guess. My main confusion was stemming from the fact that torchtyping uses type annotations. I'm heavily relying on type checkers, so it was very unexpected to see type annotations being "abused" for runtime purposes instead of type checking, and I was reading the "mostly works" as in "type checking mostly works" :wink: .

Feel free to close, since this issue can serve as documentation already.

**Comment by patrick-kidger** [comment]
Closing as you suggest.
I would highlight that runtime-type-checking isn't an abuse of type annotations; just one that performs the checks at a different time.
