### ISSUE TITLE
Showing custom types in Sphinx Docs

### ISSUE THREAD

**Issue by a-r-j** [patrick-kidger/torchtyping#42]
Hi @patrick-kidger, thanks for maintaining such a great project! :D 

I'm running into some behaviour I'd like to change when rendering docs with Sphinx. 

When I define a type it is rendered as a `torch.Tensor` in the docs e.g.:

```python
#types.py

from torchtyping import TensorType

CoordTensor = TensorType[-1, 3]
```

```python
# function.py

from .types import CoordTensor


def func(x: CoordTensor) -> CoordTensor:
    """Returns the input.

    :param x: tensor
    :type x: CoordTensor
    """"
    return x
```

![docs](https://user-images.githubusercontent.com/23709768/211603996-326ceff6-c017-4cff-b0af-11ad3e334786.png)

Do you know if there is a way to get Sphinx to show the type name I have defined (and possibly make it clickable so users can jump to the type definition in the documentation?)

**Comment by a-r-j** [comment]
I managed to resolve this:


Prevents resolving to `torch.Tensor`
```python
# types.py

from typing import NewType
from torchtyping import TensorType

CoordTensor = NewType("CoordTensor", TensorType[-1, 3])
```


And to get sphinx to render links:

```python
# conf.py

import sphinx.ext.autodoc
sphinx.ext.autodoc.NewTypeDataDocumenter.directivetype = "class"
```

**Comment by patrick-kidger** [comment]
FWIW, these days I now recommmend that folks use [jaxtyping](https://github.com/google/jaxtyping), which is pretty much a straight upgrade. Despite the name (historical reasons) it also handles PyTorch, doesn't have a JAX dependency, and it appears in documentation just fine. (At least, MkDocs-based documentation. I've not tried it with Sphinx.)
