### ISSUE TITLE
Subclassing `torch._C._TensorBase` is not supported

### ISSUE THREAD

**Issue by albanD** [patrick-kidger/torchtyping#48]
When using the latest version of PyTorch, users are seeing the following error: "RuntimeError: Cannot subclass _TensorBase directly"

https://github.com/pytorch/pytorch/issues/131463

This happens because PyTorch recently started forbidding subclassing from the raw c++ _TensorBase type in favor of subclassing torch.Tensor directly. Subclassing the base type is very unsafe as many methods on it actually assume attributes from Tensor are there and so it is not really a valid class to use ever.

Unfortunately, the trick used in https://github.com/patrick-kidger/torchtyping/blob/1f3749c5b5617ec6b6449e98ad9ae3fb6645ef54/torchtyping/tensor_type.py#L32 to create the mixing based on `type(torch.Tensor)` makes it so that the meta type sees a new class of that metatype being created without `torch.Tensor` being the base class. Hence triggering the error.

I'm not sure why we need the extra step of creating the mixin and then having the final class inherit from Tensor here https://github.com/patrick-kidger/torchtyping/blob/1f3749c5b5617ec6b6449e98ad9ae3fb6645ef54/torchtyping/tensor_type.py#L176 but avoiding the mixin and have the base class be `class TensorType(torch.Tensor, metaclass=_TensorTypeMeta):` would avoid this issue.
Not sure if that is a proper fix though.

**Comment by patrick-kidger** [comment]
Unfortunately torchtyping has long been deprecated in favour of [jaxtyping](https://github.com/patrick-kidger/jaxtyping) -- which despite the historical name, does not depend on JAX and does support PyTorch. (And does far fewer evil things under the hood... although it does still try to subclass the metaclass, do you know if it also goes wrong here?)

At any rate, I'd recommend that the issue reporter update to using jaxtyping instead!

**Comment by moe-assal** [comment]
Hello all, which version of Pytorch should I roll back to solve this issue?

**Comment by albanD** [comment]
torch < 2.4 should work in terms of releases. For nightlies would need to check a bit more carefully

Sorry for the churn here. If you think this is a going to lead to a lot of churn and cannot be worked around in dependencies, I'm willing to consider reverting that change in PyTorch, I wasn't expecting anyone to use this by side effect :/

**Comment by patrick-kidger** [comment]
I'm happy either way! I can press the button on a new release of torchtyping if need be.

**Comment by albanD** [comment]
Thanks for the quick turnaround @patrick-kidger  !
