### ISSUE TITLE
Is it possible to support python3.7

### ISSUE THREAD

**Issue by Stonesjtu** [patrick-kidger/torchtyping#7]

**Comment by AdilZouitine** [comment]
As it stands I don't think this is possible because the code is based on `typing.Annotated` which appears in python 3.9.

**Comment by patrick-kidger** [comment]
So I actually think this might be possible using `typing_extensions.Annotated` instead. I've not tried it though, or checked if anything else goes wrong. Happy to accept a PR on this. (I might get round to it myself eventually, but as a Python 3.9 user it's not a priority for me.)

**Comment by AdilZouitine** [comment]
It seem a good idea with this fix the minimum version will be python 3.5, this will allow a larger part of the community to be able to use this library.
I have some free time next week, if no one takes this PR I can take it.

**Comment by patrick-kidger** [comment]
Sounds good, thanks. I don't think there's much worry about going below Python 3.7 though, as PyTorch will soon be dropping support for anything below that. (And in any case would require a bit of extra work, as `__class_getitem__` is Python 3.7+)

**Comment by AdilZouitine** [comment]
Got it !

**Comment by patrick-kidger** [comment]
Closed by #11.
